### ISSUE TITLE
Adding waiting time

### ISSUE THREAD

**Issue by joachimBrindeau** [quantumsheep/7speaking-bot#2]
Hey !

This script is life-saving.

In addition to the tests, I'm supposed to spend a minimum of 40 hours learning english despite not needing it at all.
Is there any way you could guide me in adding a timer to the script so that it will wait half an hour on each exercise?
![Capture d’écran 2022-03-10 à 15 44 14](https://user-images.githubusercontent.com/6870905/157686144-ac98d171-102d-4904-ba08-258072178ac3.png)

Thanks again !

**Comment by quantumsheep** [comment]
You can try to extend the wait calls in `7speaking.user.js`

**Comment by joachimBrindeau** [comment]
Thanks, I'm not a developper at all.
I just like to tinker with stuff.

In order for the script to wait 500 seconds, I've tried adding : "await wait(500000);"
On line 304

Guess that's not it (probably stupid but I've no idea what I'm doing).
Would you mind telling me more please?

**Comment by quantumsheep** [comment]
It should be good if you're doing a workshop, what's your URL ?

**Comment by joachimBrindeau** [comment]
Ah yeah, I actually need to wait on "https://user.7speaking.com/document/..."

**Comment by quantumsheep** [comment]
The bot is supposed to start the test when in `/document`, once the test has started, what is your URL ?

**Comment by joachimBrindeau** [comment]
Yes it does start the quizz https://user.7speaking.com/quiz/news/10876?isoct=0

Everything works fine, I would just like it to wait when he is on the `/document` page.
So I can do 40 hours without doing an unrealistic one thousand tests.

**Comment by quantumsheep** [comment]
> I would just like it to wait when he is on the `/document` page

Adding a `await wait(500000)` at line 310 should work then :)

**Comment by joachimBrindeau** [comment]
It works ! Thanks a lot !

**Comment by quantumsheep** [comment]
Enjoy your free time not being forced to do 7Speaking 🥳
